### ISSUE TITLE
When is Hello() ever called

### ISSUE THREAD

**Issue by ghost** [iheanyi/go-grpc-graphql-simple-example#2]
Hi, just curious as I am learning as well...

When is this function ever called in the code?
```
func (r *Resolver) Hello(ctx context.Context, args struct{ Name string }) (string, error) {
	request := &api.SayHelloReq{
		Name: args.Name,
	}

	res, err := r.helloSvc.SayHello(ctx, request)
	if err != nil {
		return "", err
	}

	return res.Message, nil
}
```

the query defines a lowercase hello() function, just not sure how graphql makes the link between hello() and Hello()

**Comment by iheanyi** [comment]
Hey there @sc4224,

`GraphQL-Go` will know that the hello query corresponds to `Hello` since their names are the same. When the client makes a query to the GraphQL API server with the `hello` query, then the Go service will execute the `Hello` function to return the data back to the client. :) Hope this helps clears things up, let me know if you have more questions.
